### ISSUE TITLE
SubjectA HFreq 

### ISSUE THREAD

**Issue by HaneenSu** [gifale95/eeg_motor_imagery_decoding#2]
Hi

Thanks for the wonderful work. Just wondering if you tried your code on Subject A HFREQ data (1000 Hz sampling). 
Is there a reason it was not selected? I tried to work on this file using my model and for some reason it doesn't train at all (chance level). Just wondering if you faced the same issue. 

Thanks

**Comment by gifale95** [comment]
Hey,

Yes, when training my decoding models on the 5F dataset HFREQ 1000Hz data my decoding accuracy also remained at chance. Back then I was getting in touch with the people who collected the dataset, who wrote me the following:

> "_The accuracy would depend on the algorithm and it is difficult for me to say anything without knowing what you did. 1000hz data would have a lot more features than 200hz, so feature selection and regularization would play a lot more critical role. I found that in that particular eeg device the data above about 100 hz looked essentially like white noise. So if you are just feeding all the 1000hz data in a ML algorithm without doing anything else, it may be like adding a lot of white noise too your features, and will degrade performance. Other than that it is really hard to say anything without knowing specifics. Try filter down the 1000 hz datasets with low be pass 100 hz and see if can get back the accuracy._"

So I then downsampled the HFREQ 1000Hz data to 100Hz, and the decoding worked well.

**Comment by HaneenSu** [comment]
Thank you for your response. However, I noticed that you didn't include the HFRQ data for subject A particularly (but you included it for other subjects). I downsampled subject A HFREQ file and that didn't impact the classification accuracy (it stayed at chance level). Did you succeed with Subject A HFREQ?

**Comment by gifale95** [comment]
Yes, I didn't include the HFRQ data for subjects A and B exactly for this reason: when I was downsampling their data to 100Hz, the decoding accuracy still remained at chance.

**Comment by HaneenSu** [comment]
Wonderful thanks for the confirmation. It is so weird that some research work report high accuracies (70%) for this specific file. This is unexplainable to me, and I am glad you confirmed my observation:
https://www.mdpi.com/2227-7390/10/13/2302
https://www.mdpi.com/2227-7390/9/24/3297
